### ISSUE TITLE
无字重变化

### ISSUE THREAD

**Issue by ThreeManager785** [Partyb0ssishere/cef-fonts-cjk#2]
现在的字体貌似没有粗体和其他版本。
请问有计划增加其他字重吗？还是不打算设计。

**Comment by Partyb0ssishere** [comment]
如果真的要做粗体我会疯掉的。  
  
首先单个字符的锚点数量特别多，不便调整，其次，虽然  FontCreator  可以机械加粗，但一是有的字符加粗之后笔画会糊在一起，二是这个功能有bug，可能导致字符轮廓异常。  
  
所以我无力制作粗体，非常抱歉。  
  
如果实在需要，可以考虑此 Fork：  
https://github.com/Losketch/cef-fonts-cjk
