### ISSUE TITLE
[Enhancement] 多使用 Tags 和 Releases

### ISSUE THREAD

**Issue by I21b** [Partyb0ssishere/cef-fonts-cjk#3]

**Comment by pugaizai** [comment]
zici

**Comment by Partyb0ssishere** [comment]
感谢您的提议，不过 Release 目前应该不会在本项目中使用。原因有二：  
- **本字体并非完美**  
CEF Fonts CJK中有很多东西还没做完，比如西文的 Kerning 和谚文组字功能。我做字使用的软件是 FontCreator ，目前字体工程体积庞大，编辑 Opentype 特性时每一次操作至少需要2秒才能响应，体验可谓**极其恶心**，所以这些未完成的东西就都被放弃维护了。  
- **关于中国大陆用户**  
Github 在中国大陆的访问速度不言自明，如果采用 Release ，将导致不弚觑武帊轑的人完全不能下载字体。  

不过以上问题都可以通过**开设姊妹项目**解决。我目前正在做一个更好的西文字体“CEF Fonts ?????”，该项目正式发布时将不会有未完成遗留，同时正常使用 Release 发布，敬请期待。  
另外，目前我有开一个类似“CEF Fonts CJK Pro”的姊妹项目的想法，但目前仍在计划中，未开始实施。

**Comment by oldherl** [comment]
release 不是只有最后完成的、不再修改的版本才能使用的。一个正常的项目可以（也应该）多次发布版本，且每一个版本都应留存供以后下载，而不是将上一次的文件删除再放上新的。

**Comment by wenkeming** [comment]
> release 不是只有最后完成的、不再修改的版本才能使用的。一个正常的项目可以（也应该）多次发布版本，且每一个版本都应留存供以后下载，而不是将上一次的文件删除再放上新的。

同意，如果不发release最好也加上版本号，不然下载的是不是最新的可能都不知道

**Comment by Partyb0ssishere** [comment]
从 v2.25 开始将使用 Release 发布主要版本。

**Comment by Losketch** [comment]
发Release其实可以用7zip压缩一下再发
有部分人不方便下载，
具体是→添加到压缩包→压缩格式zip或7z都行

zip：压缩等级9，压缩方法LZMA，字典大小256或512MB或更大，单词大小默认，其它默认
7z：压缩等级9，压缩方法LZMA2，字典大小同上，单词大小默认，其它默认

当然tar.gz也不是不行

**Comment by I21b** [comment]
> 发Release其实可以用7zip压缩一下再发
> 有部分人不方便下载，
> 具体是→添加到压缩包→压缩格式zip或7z都行
> 
> zip：压缩等级9，压缩方法LZMA，字典大小256或512MB或更大，单词大小默认，其它默认
> 7z：压缩等级9，压缩方法LZMA2，字典大小同上，单词大小默认，其它默认
> 
> 当然tar.gz也不是不行

用source code zip下载就行
