### ISSUE TITLE
The readability of ASCII characters needs to be improved

### ISSUE THREAD

**Issue by inkbottle-9** [Partyb0ssishere/cef-fonts-cjk#5]
# ASCII 字符的可读性有待提升

![image](https://github.com/Partyb0ssishere/cef-fonts-cjk/assets/55432702/c9231830-6d6f-4646-8add-f34eea338ef7)

默认字重时 CEF 字体 (等宽版本) 整体较细, ASCII 字符的字体间距过低, 在某些暗色颜色下可读性较差
(相较于 Sarasa 等黑体)

![image](https://github.com/Partyb0ssishere/cef-fonts-cjk/assets/55432702/a0dacc24-860b-451c-af8a-96c473fb5f71)

使用粗体进一步加剧了 ASCII 字符间距过低的问题

可以考虑适当减少 ASCII 字符的字面率 (水平方向) 以提升可读性

**Comment by Partyb0ssishere** [comment]
事实上无论是等宽版还是非等宽版都有这样的问题。但目前这个字体项目的西文部分已经放弃维护了，所以非常抱歉，这大概不会被修复。

我正在做一个更好的西文字体，这个新字体的间距问题将得到一定程度的改善。
（样图为非等宽版，第一版发布时也会提供等宽版本。）

![Image_1719412592898.png](https://github.com/Partyb0ssishere/cef-fonts-cjk/assets/106015739/d537c394-6893-45a1-b72b-f6d3e687f301)

**Comment by inkbottle-9** [comment]
> 事实上无论是等宽版还是非等宽版都有这样的问题。但目前这个字体项目的西文部分已经放弃维护了，所以非常抱歉，这大概不会被修复。
> 
> 我正在做一个更好的西文字体，这个新字体的间距问题将得到一定程度的改善。 （样图为非等宽版，第一版发布时也会提供等宽版本。）

挺好的. 到时候或许可以直接把这个新字体的西文部分合并到 CEF 上. 额, 或者把 CEF 的其它部分合并到新字体? 无意冒犯, 我不是很清楚这其中是否有困难. 据我所知, Sarasa 更纱黑体是由 Iosevka 和 Source Han Sans 合并而来, 该字体在各种环境下 (shell, 粗体, 中英混合等) 表现都非常出色, 也许有值得借鉴的设计

此外, 虽然不甚了解, 但我对这个还挺感兴趣的, 你需要什么帮助吗?

**Comment by Partyb0ssishere** [comment]
我在 Issue #3 提了 CEF Fonts CJK 的西文部分为何放弃维护。至于您提到的：  
> 到时候或许可以直接把这个新字体的西文部分合并到 CEF 上. 额, 或者把 CEF 的其它部分合并到新字体?  
  
目前我考虑这样做，只不过不是在这个项目，而是另起炉灶。
